version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./db/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    ports:
      - 4444:4444
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

networks:
  postgres-network:
    driver: bridge
  web:
    driver: bridge
